/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Gearbox.glb -t 
*/

/// <reference types="@react-three/fiber" />

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    body_3: THREE.Mesh
    body_4: THREE.Mesh
    body_5: THREE.Mesh
    body_6: THREE.Mesh
    body_7_instance_0: THREE.Mesh
    body_8_instance_0: THREE.Mesh
    body_7_instance_1: THREE.Mesh
    body_9_instance_0: THREE.Mesh
    body_10_instance_0: THREE.Mesh
    body_11: THREE.Mesh
    body_instance_0: THREE.Mesh
    body_1: THREE.Mesh
    body_2_instance_0: THREE.Mesh
    mesh_31: THREE.Mesh
    mesh_30: THREE.Mesh
    mesh_29: THREE.Mesh
    mesh_28: THREE.Mesh
    mesh_27: THREE.Mesh
    body_8_instance_1: THREE.Mesh
    mesh_25: THREE.Mesh
    body_9_instance_1: THREE.Mesh
    body_10_instance_1: THREE.Mesh
    mesh_22: THREE.Mesh
    body_instance_1: THREE.Mesh
    mesh_33: THREE.Mesh
    body_2_instance_1: THREE.Mesh
    body_16_instance_1: THREE.Mesh
    body_18: THREE.Mesh
    body_15_instance_1: THREE.Mesh
    body_16_instance_0: THREE.Mesh
    body_17: THREE.Mesh
    body_12: THREE.Mesh
    body_13: THREE.Mesh
    body_14: THREE.Mesh
    body_15_instance_0: THREE.Mesh
    body_20_instance_0: THREE.Mesh
    body_20_instance_1: THREE.Mesh
    body_20_instance_2: THREE.Mesh
    body_21_instance_0: THREE.Mesh
    body_21_instance_1: THREE.Mesh
    body_21_instance_2: THREE.Mesh
    body_21_instance_3: THREE.Mesh
    body_21_instance_4: THREE.Mesh
    body_21_instance_5: THREE.Mesh
    body_22_instance_0: THREE.Mesh
    body_22_instance_1: THREE.Mesh
    body_23_instance_0: THREE.Mesh
    body_23_instance_1: THREE.Mesh
    body_24_instance_0: THREE.Mesh
    body_25_instance_0: THREE.Mesh
    body_26_instance_0: THREE.Mesh
    body_27_instance_0: THREE.Mesh
    body_28_instance_0: THREE.Mesh
    body_29_instance_0: THREE.Mesh
    body_29_instance_1: THREE.Mesh
    body_29_instance_2: THREE.Mesh
    body_21_instance_12: THREE.Mesh
    body_21_instance_13: THREE.Mesh
    body_21_instance_14: THREE.Mesh
    mesh_13: THREE.Mesh
    body_31_instance_0: THREE.Mesh
    body_31_instance_1: THREE.Mesh
    body_31_instance_2: THREE.Mesh
    body_30: THREE.Mesh
    body_19_instance_0: THREE.Mesh
    body_20_instance_3: THREE.Mesh
    body_20_instance_4: THREE.Mesh
    body_20_instance_5: THREE.Mesh
    body_21_instance_6: THREE.Mesh
    body_21_instance_7: THREE.Mesh
    body_21_instance_8: THREE.Mesh
    body_21_instance_9: THREE.Mesh
    body_21_instance_10: THREE.Mesh
    body_21_instance_11: THREE.Mesh
    body_22_instance_2: THREE.Mesh
    body_22_instance_3: THREE.Mesh
    body_23_instance_2: THREE.Mesh
    body_23_instance_3: THREE.Mesh
    body_24_instance_1: THREE.Mesh
    body_25_instance_1: THREE.Mesh
    body_26_instance_1: THREE.Mesh
    body_27_instance_1: THREE.Mesh
    body_28_instance_1: THREE.Mesh
    body_29_instance_3: THREE.Mesh
    body_29_instance_4: THREE.Mesh
    body_29_instance_5: THREE.Mesh
    body_21_instance_15: THREE.Mesh
    body_21_instance_16: THREE.Mesh
    body_21_instance_17: THREE.Mesh
    body_24_instance_2: THREE.Mesh
    body_31_instance_3: THREE.Mesh
    body_31_instance_4: THREE.Mesh
    body_31_instance_5: THREE.Mesh
    mesh_3: THREE.Mesh
    body_19_instance_1: THREE.Mesh
  }
  materials: {
    Material_13: THREE.MeshStandardMaterial
    Material_16: THREE.MeshStandardMaterial
    Material_15: THREE.MeshStandardMaterial
    Material_14: THREE.MeshStandardMaterial
    Material_17: THREE.MeshStandardMaterial
    Material_12: THREE.MeshStandardMaterial
    default_2: THREE.MeshStandardMaterial
  }
  animations: any[]
}

//When you delete the duplicate Material_13 lines at the top of your .tsx file, 
// you are not touching the 3D model itself. You are only fixing a TypeScript Dictionary.
// Think of that top section of code as a dictionary or a glossary.
//     If you write a book, and the word "Bolt" appears 50 times in the story, you don't put the word "Bolt" in the glossary 50 times. You put it in the glossary once.
//     Because the 3D software exported poorly, it accidentally wrote Material_13 in the glossary 5 times. Deleting 4 of them just fixes the glossary so TypeScript stops complaining. The 50 bolts in the actual code below it will still render perfectly using that one glossary definition.
export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Gearbox.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[155.796, 8.459, -37.11]}>
        <group position={[-2.45, 9.403, 38.391]} rotation={[0, 0, 2.094]}>
          <group position={[0, 0, 4.926]}>
            <mesh geometry={nodes.body_5.geometry} material={materials.Material_13} position={[0, 0, 0.9]} />
            <mesh geometry={nodes.body_6.geometry} material={materials.Material_13} />
          </group>
          <group position={[0, 0, 2.666]} rotation={[0, 0, Math.PI / 6]}>
            <mesh geometry={nodes.body_7_instance_0.geometry} material={materials.Material_13} position={[0, 0, -0.28]} rotation={[-Math.PI / 2, 0, Math.PI]} />
            <mesh geometry={nodes.body_8_instance_0.geometry} material={materials.Material_16} />
          </group>
          <group position={[0, 0, 0.376]}>
            <mesh geometry={nodes.body_7_instance_1.geometry} material={materials.Material_13} position={[0, 0, 1.72]} rotation={[-Math.PI / 2, Math.PI / 3, 0]} />
            <mesh geometry={nodes.body_9_instance_0.geometry} material={materials.Material_15} position={[0, 0, 5.185]} rotation={[0, 0, Math.PI]} />
            {/* Pressure Plate */}
            <mesh geometry={nodes.body_10_instance_0.geometry} material={materials.Material_14} position={[0, 0, 1.53]} rotation={[0, 0, -Math.PI / 3]} />
            {/* Pressure Plate */}
            <mesh geometry={nodes.body_11.geometry} material={materials.Material_13} position={[0, 0, 5.15]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes.body_instance_0.geometry} material={materials.Material_17} position={[0, 0, 3.916]} />
          <mesh geometry={nodes.body_1.geometry} material={materials.Material_13} position={[0, 0, 5.606]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.body_2_instance_0.geometry} material={materials.Material_12} position={[0, 0, 6.831]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.body_3.geometry} material={materials.Material_13} />
          <mesh geometry={nodes.body_4.geometry} material={materials.Material_13} />
        </group>
        <group position={[8.44, 9.403, 38.391]} rotation={[0, 0, -2.094]}>
          <group position={[0, 0, 4.926]}>
            <mesh geometry={nodes.mesh_29.geometry} material={materials.default_2} position={[0, 0, 0.9]} />
            <mesh geometry={nodes.mesh_28.geometry} material={materials.default_2} />
          </group>
          <group position={[0, 0, 2.666]} rotation={[0, 0, Math.PI / 6]}>
            <mesh geometry={nodes.mesh_27.geometry} material={materials.default_2} position={[0, 0, -0.28]} rotation={[-Math.PI / 2, 0, Math.PI]} />
            <mesh geometry={nodes.body_8_instance_1.geometry} material={materials.Material_16} />
          </group>
          <group position={[0, 0, 0.376]}>
            <mesh geometry={nodes.mesh_25.geometry} material={materials.default_2} position={[0, 0, 1.72]} rotation={[-Math.PI / 2, Math.PI / 3, 0]} />
            <mesh geometry={nodes.body_9_instance_1.geometry} material={materials.Material_15} position={[0, 0, 5.185]} rotation={[0, 0, Math.PI]} />
            <mesh geometry={nodes.body_10_instance_1.geometry} material={materials.Material_14} position={[0, 0, 1.53]} rotation={[0, 0, -Math.PI / 3]} />
            <mesh geometry={nodes.mesh_22.geometry} material={materials.default_2} position={[0, 0, 5.15]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes.body_instance_1.geometry} material={materials.Material_17} position={[0, 0, 3.916]} />
          <mesh geometry={nodes.mesh_33.geometry} material={materials.default_2} position={[0, 0, 5.606]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.body_2_instance_1.geometry} material={materials.Material_12} position={[0, 0, 6.831]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_31.geometry} material={materials.default_2} />
          <mesh geometry={nodes.mesh_30.geometry} material={materials.default_2} />
        </group>
        <group position={[2.995, 6.507, 37.167]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -3.3, 0]} rotation={[Math.PI, -Math.PI / 2, 0]}>
            <group position={[-3.8, 8.006, 0]}>
              <mesh geometry={nodes.body_16_instance_1.geometry} material={materials.Material_14} position={[2.1, 0, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
              <mesh geometry={nodes.body_18.geometry} material={materials.Material_15} />
            </group>
            <mesh geometry={nodes.body_15_instance_1.geometry} material={materials.default_2} position={[0, -0.53, 0]} />
            <mesh geometry={nodes.body_16_instance_0.geometry} material={materials.Material_14} position={[0, 6.256, 0]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.body_17.geometry} material={materials.default_2} position={[0, 0.25, 0]} rotation={[0, 0, Math.PI / 2]} />
          </group>
          <mesh geometry={nodes.body_12.geometry} material={materials.default_2} position={[0, -3.05, 0]} />
          <mesh geometry={nodes.body_13.geometry} material={materials.Material_15} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.body_14.geometry} material={materials.default_2} />
          <mesh geometry={nodes.body_15_instance_0.geometry} material={materials.default_2} position={[0, -2.53, 0]} />
        </group>
        <group position={[14.775, 5.745, 43.317]} rotation={[Math.PI / 2, -Math.PI / 6, 0]}>
          <group position={[0, -8.109, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            {/* Bolt */}
            <mesh geometry={nodes.body_20_instance_0.geometry} material={materials.Material_12} position={[0.89, 1.542, 0.672]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_20_instance_1.geometry} material={materials.Material_12} position={[0.891, -1.542, 0.672]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_20_instance_2.geometry} material={materials.Material_12} position={[-1.781, 0, 0.672]} rotation={[-Math.PI, 0, -Math.PI]} />
            {/* Bolt */}

            <mesh geometry={nodes.body_21_instance_0.geometry} material={materials.Material_12} position={[0.891, -1.542, 5.429]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_21_instance_1.geometry} material={materials.Material_12} position={[-1.781, 0, 5.429]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_21_instance_2.geometry} material={materials.Material_12} position={[0.89, 1.542, 5.429]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_21_instance_3.geometry} material={materials.Material_12} position={[0.89, 1.542, -0.571]} />
            <mesh geometry={nodes.body_21_instance_4.geometry} material={materials.Material_12} position={[0.891, -1.542, -0.571]} />
            <mesh geometry={nodes.body_21_instance_5.geometry} material={materials.Material_12} position={[-1.781, 0, -0.571]} />
            <mesh geometry={nodes.body_22_instance_0.geometry} material={materials.default_2} position={[0, 0, -0.311]} />
            <mesh geometry={nodes.body_22_instance_1.geometry} material={materials.default_2} position={[0, 0, 5.3]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_23_instance_0.geometry} material={materials.Material_12} position={[0, 0, 5.63]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_23_instance_1.geometry} material={materials.Material_12} position={[0, 0, -0.641]} />
            <mesh geometry={nodes.body_24_instance_0.geometry} material={materials.default_2} position={[0, 0, -0.11]} rotation={[Math.PI, 0, -2.618]} />
            <mesh geometry={nodes.body_25_instance_0.geometry} material={materials.Material_14} position={[0, 0, 5.21]} rotation={[0, 0, Math.PI / 3]} />
            <mesh geometry={nodes.body_26_instance_0.geometry} material={materials.Material_12} position={[0, 0, 4.681]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.body_27_instance_0.geometry} material={materials.default_2} position={[0, 0, 2.494]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_28_instance_0.geometry} material={materials.default_2} position={[0, 0, -0.311]} rotation={[Math.PI, 0, -2.618]} />
            {/* Bolt */}
            <mesh geometry={nodes.body_29_instance_0.geometry} material={materials.Material_12} position={[0.891, -1.542, 3.578]} />
            <mesh geometry={nodes.body_29_instance_1.geometry} material={materials.Material_12} position={[-1.781, 0, 3.578]} />
            <mesh geometry={nodes.body_29_instance_2.geometry} material={materials.Material_12} position={[0.89, 1.542, 3.578]} />
            {/* Bolt */}

          </group>
          <group position={[0, -43.14, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <group position={[0, 0, 40.438]}>
              <mesh geometry={nodes.body_21_instance_12.geometry} material={materials.Material_12} position={[1.542, -0.89, 0.27]} />
              <mesh geometry={nodes.body_21_instance_13.geometry} material={materials.Material_12} position={[0, 1.781, 0.27]} />
              <mesh geometry={nodes.body_21_instance_14.geometry} material={materials.Material_12} position={[-1.542, -0.891, 0.27]} />
              <mesh geometry={nodes.mesh_13.geometry} material={materials.Material_13} position={[0, 0, 1.091]} rotation={[0, 0, -2.094]} />
            {/* Bolt */}
              <mesh geometry={nodes.body_31_instance_0.geometry} material={materials.Material_12} position={[1.542, -0.89, 1.247]} rotation={[-Math.PI, 0, -Math.PI]} />
              <mesh geometry={nodes.body_31_instance_1.geometry} material={materials.Material_12} position={[0, 1.781, 1.247]} rotation={[-Math.PI, 0, -Math.PI]} />
              <mesh geometry={nodes.body_31_instance_2.geometry} material={materials.Material_12} position={[-1.542, -0.891, 1.247]} rotation={[-Math.PI, 0, -Math.PI]} />
            {/* Bolt */}

            </group>
            <mesh geometry={nodes.body_30.geometry} material={materials.Material_13} position={[0, 0, 30.49]} />
          </group>
          <mesh geometry={nodes.body_19_instance_0.geometry} material={materials.Material_12} position={[0, 0.805, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
        </group>
        <group position={[-8.785, 5.745, 43.317]} rotation={[-Math.PI / 2, -Math.PI / 6, Math.PI]}>
          <group position={[0, -8.109, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh geometry={nodes.body_20_instance_3.geometry} material={materials.Material_12} position={[0.891, 1.542, 0.672]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_20_instance_4.geometry} material={materials.Material_12} position={[0.89, -1.542, 0.672]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_20_instance_5.geometry} material={materials.Material_12} position={[-1.781, 0, 0.672]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_21_instance_6.geometry} material={materials.Material_12} position={[0.89, -1.542, 5.429]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_21_instance_7.geometry} material={materials.Material_12} position={[-1.781, 0, 5.429]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_21_instance_8.geometry} material={materials.Material_12} position={[0.891, 1.542, 5.429]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_21_instance_9.geometry} material={materials.Material_12} position={[0.891, 1.542, -0.571]} />
            <mesh geometry={nodes.body_21_instance_10.geometry} material={materials.Material_12} position={[0.89, -1.542, -0.571]} />
            <mesh geometry={nodes.body_21_instance_11.geometry} material={materials.Material_12} position={[-1.781, 0, -0.571]} />
            <mesh geometry={nodes.body_22_instance_2.geometry} material={materials.default_2} position={[0, 0, -0.311]} />
            <mesh geometry={nodes.body_22_instance_3.geometry} material={materials.default_2} position={[0, 0, 5.3]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_23_instance_2.geometry} material={materials.Material_12} position={[0, 0, 5.63]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_23_instance_3.geometry} material={materials.Material_12} position={[0, 0, -0.641]} />
            <mesh geometry={nodes.body_24_instance_1.geometry} material={materials.default_2} position={[0, 0, -0.11]} rotation={[Math.PI, 0, -2.618]} />
            <mesh geometry={nodes.body_25_instance_1.geometry} material={materials.Material_14} position={[0, 0, 5.21]} rotation={[0, 0, Math.PI / 3]} />
            <mesh geometry={nodes.body_26_instance_1.geometry} material={materials.Material_12} position={[0, 0, 4.681]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.body_27_instance_1.geometry} material={materials.default_2} position={[0, 0, 2.494]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.body_28_instance_1.geometry} material={materials.default_2} position={[0, 0, -0.311]} rotation={[Math.PI, 0, -2.618]} />
            <mesh geometry={nodes.body_29_instance_3.geometry} material={materials.Material_12} position={[0.89, -1.542, 3.578]} />
            <mesh geometry={nodes.body_29_instance_4.geometry} material={materials.Material_12} position={[-1.781, 0, 3.578]} />
            <mesh geometry={nodes.body_29_instance_5.geometry} material={materials.Material_12} position={[0.891, 1.542, 3.578]} />
          </group>
          <group position={[0, -43.14, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <group position={[0, 0, 40.438]}>
              <mesh geometry={nodes.body_21_instance_15.geometry} material={materials.Material_12} position={[1.542, -0.891, 0.27]} />
              <mesh geometry={nodes.body_21_instance_16.geometry} material={materials.Material_12} position={[0, 1.781, 0.27]} />
              <mesh geometry={nodes.body_21_instance_17.geometry} material={materials.Material_12} position={[-1.542, -0.89, 0.27]} />
              <mesh geometry={nodes.body_24_instance_2.geometry} material={materials.default_2} position={[0, 0, 1.091]} rotation={[0, 0, -2.094]} />
              <mesh geometry={nodes.body_31_instance_3.geometry} material={materials.Material_12} position={[1.542, -0.891, 1.247]} rotation={[-Math.PI, 0, -Math.PI]} />
              <mesh geometry={nodes.body_31_instance_4.geometry} material={materials.Material_12} position={[0, 1.781, 1.247]} rotation={[-Math.PI, 0, -Math.PI]} />
              <mesh geometry={nodes.body_31_instance_5.geometry} material={materials.Material_12} position={[-1.542, -0.89, 1.247]} rotation={[-Math.PI, 0, -Math.PI]} />
            </group>
            <mesh geometry={nodes.mesh_3.geometry} material={materials.default_2} position={[0, 0, 30.49]} />
          </group>
          <mesh geometry={nodes.body_19_instance_1.geometry} material={materials.Material_12} position={[0, 0.805, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={1000000} near={0.05} fov={15.083} position={[207.615, 53.328, 51.621]} rotation={[-0.644, 0.675, 0.438]} />
    </group>
  )
}

useGLTF.preload('/Gearbox.glb')
